version: '2'
services:
  database:
    image: postgres:14
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=easyscan"
    ports:
    - "5432:5432"
volumes:
  data-volume:
